version: '3'

services:
  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    restart: "no"
    networks:
      - app_net
  redis:
    image: redis:5.0.5
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - app_net
    volumes:
      - redis-data:/data
  rabbit:
    image: rabbitmq:3.6.6-management
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
    networks:
      - app_net
  celery:
    build: .
    env_file: .env
    command: celery worker -A apps.celery -l info --concurrency=10 -n worker1@%h
    volumes:
      - .:/code
    networks:
      - app_net
  celery-beat:
    env_file: .env
    build: .
    command: celery beat -A apps.celery -s celerybeat-schedule -l info
    volumes:
      - .:/code
    networks:
      - app_net
  web:
    build: .
    env_file: .env
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbit
      - celery
      - celery-beat
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  redis-data:
