version: '3'

services:
  db:
    ports: []
    networks:
      - app_net
  localstack:
    image: localstack/localstack:latest
    env_file: .env
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./utils/bucket_create.sh:/utils/bucket_create.sh
      - .localstack:/tmp/localstack
    networks:
      - app_net
  web:
    image: "${APP_NAME}_${APP_HASH}"
    build:
      context: .
      args:
        - TEST="true"
    ports: []
    depends_on:
      - db
      - localstack
    networks:
      - app_net

networks:
  app_net:
    driver: bridge