# Generated by Django 2.2.4 on 2019-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('media', '0005_auto_20190909_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('songs_amount', models.PositiveSmallIntegerField(default=0)),
                ('is_private', models.BooleanField()),
                ('songs', models.ManyToManyField(related_name='playlists',
                                                 to='media.Song')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.ImageField(default=None, upload_to='media/')),
                ('is_staff', models.BooleanField()),
                ('followers',
                 models.ManyToManyField(blank=True, related_name='users',
                                        to='user.User')),
                ('liked_songs',
                 models.ManyToManyField(blank=True, related_name='users',
                                        to='media.Song')),
                ('playlists',
                 models.ManyToManyField(blank=True, related_name='users',
                                        to='user.Playlist')),
            ],
        ),
    ]
