# Generated by Django 2.2.4 on 2019-09-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_amount',
            field=models.IntegerField(default=0),
        ),
    ]
