# Generated by Django 2.2.4 on 2019-09-20 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_auto_20190913_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playlists',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
