# Generated by Django 2.2.4 on 2019-09-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190923_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_songs',
        ),
    ]
