# Generated by Django 2.2.4 on 2019-09-27 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('likes', '0002_auto_20190927_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_type',
        ),
    ]
