# Generated by Django 2.2.4 on 2019-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='listens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
