# Generated by Django 2.2.4 on 2019-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media', '0003_auto_20190901_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums',
                                         to='media.Song'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
