# Generated by Django 2.2.4 on 2019-09-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20190902_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='genre',
            new_name='genres',
        ),
    ]
