# Generated by Django 2.2.4 on 2019-09-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20190909_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.URLField(default='image.png'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.URLField(default='image.png'),
        ),
        migrations.AlterField(
            model_name='song',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.URLField(default='image.png'),
        ),
    ]
